In [2]:
from pynwb import NWBHDF5IO
#import nwbwidgets as nw

io = NWBHDF5IO("S10_DTU.nwb", "r")
nwb = io.read()

#table
print("-------------Trial Table-----------")
trials_df = nwb.trials.to_dataframe()
trials_df["duration_min"] = (trials_df["stop_time"] - trials_df["start_time"]) / 60
trials_df

-------------Trial Table-----------

,start_time,stop_time,dataset,attended_ear,stim_L_name,stim_R_name,n_speakers,attend_mf,attend_lr,stim_male_name,stim_female_name,trigger,acoustic_condition,start_sample,stop_sample,duration_min
id,,,,,,,,,,,,,,,,
0,49.539062,133.005859,DTU,left,marianne_story4_trial_1.wav,aske_story1_trial_1.wav,2,2,1,aske_story1_trial_1.wav,marianne_story4_trial_1.wav,192,1,25364,68099,1.391113
1,133.005859,215.718750,DTU,right,aske_story1_trial_2.wav,marianne_story4_trial_2.wav,2,2,2,aske_story1_trial_2.wav,marianne_story4_trial_2.wav,131,3,68099,110448,1.378548
2,215.718750,294.451172,DTU,right,aske_story1_trial_3.wav,marianne_story4_trial_3.wav,2,2,2,aske_story1_trial_3.wav,marianne_story4_trial_3.wav,131,3,110448,150759,1.312207
3,294.451172,453.191406,DTU,right,aske_story1_trial_4.wav,marianne_story4_trial_4.wav,2,2,2,aske_story1_trial_4.wav,marianne_story4_trial_4.wav,150,2,150759,232034,2.645671
4,526.035156,606.173828,DTU,right,aske_story1_trial_5.wav,marianne_story4_trial_5.wav,2,2,2,aske_story1_trial_5.wav,marianne_story4_trial_5.wav,135,1,269330,310361,1.335645
5,606.173828,698.863281,DTU,right,aske_story1_trial_6.wav,marianne_story4_trial_6.wav,2,2,2,aske_story1_trial_6.wav,marianne_story4_trial_6.wav,150,2,310361,357818,1.544824
6,801.908203,882.822266,DTU,left,marianne_story4_trial_7.wav,aske_story1_trial_7.wav,2,2,1,aske_story1_trial_7.wav,marianne_story4_trial_7.wav,192,1,410577,452005,1.348568
7,882.822266,956.382812,DTU,left,marianne_story4_trial_8.wav,aske_story1_trial_8.wav,2,2,1,aske_story1_trial_8.wav,marianne_story4_trial_8.wav,224,3,452005,489668,1.226009
8,1098.175781,1202.287109,DTU,right,aske_story1_trial_9.wav,marianne_story4_trial_9.wav,2,2,2,aske_story1_trial_9.wav,marianne_story4_trial_9.wav,131,3,562266,615571,1.735189
9,1202.287109,1360.037109,DTU,right,aske_story1_trial_10.wav,marianne_story4_trial_10.wav,2,2,2,aske_story1_trial_10.wav,marianne_story4_trial_10.wav,131,3,615571,696339,2.629167
10,1360.037109,1450.669922,DTU,left,marianne_story4_trial_11.wav,aske_story1_trial_11.wav,2,2,1,aske_story1_trial_11.wav,marianne_story4_trial_11.wav,133,2,696339,742743,1.510547
11,1450.669922,1529.929688,DTU,left,marianne_story4_trial_12.wav,aske_story1_trial_12.wav,2,2,1,aske_story1_trial_12.wav,marianne_story4_trial_12.wav,192,1,742743,783324,1.320996
12,1529.929688,1610.554688,DTU,left,marianne_story4_trial_13.wav,aske_story2_trial_1.wav,2,2,1,aske_story2_trial_1.wav,marianne_story4_trial_13.wav,133,2,783324,824604,1.343750
13,1610.554688,1701.523438,DTU,left,marianne_story4_trial_14.wav,aske_story2_trial_2.wav,2,2,1,aske_story2_trial_2.wav,marianne_story4_trial_14.wav,192,1,824604,871180,1.516146
14,1701.523438,1786.535156,DTU,left,marianne_story4_trial_15.wav,aske_story2_trial_3.wav,2,2,1,aske_story2_trial_3.wav,marianne_story4_trial_15.wav,224,3,871180,914706,1.416862
15,1786.535156,1885.554688,DTU,left,marianne_story4_trial_16.wav,aske_story2_trial_4.wav,2,2,1,aske_story2_trial_4.wav,marianne_story4_trial_16.wav,133,2,914706,965404,1.650326
16,1885.554688,1968.761719,DTU,right,aske_story2_trial_5.wav,marianne_story4_trial_17.wav,2,2,2,aske_story2_trial_5.wav,marianne_story4_trial_17.wav,150,2,965404,1008006,1.386784
17,1968.761719,2246.080078,DTU,left,marianne_story4_trial_18.wav,aske_story2_trial_6.wav,2,2,1,aske_story2_trial_6.wav,marianne_story4_trial_18.wav,133,2,1008006,1149993,4.621973
18,2246.080078,2320.798828,DTU,right,aske_story2_trial_7.wav,marianne_story4_trial_19.wav,2,2,2,aske_story2_trial_7.wav,marianne_story4_trial_19.wav,150,2,1149993,1188249,1.245313
19,2320.798828,2397.283203,DTU,left,marianne_story4_trial_20.wav,aske_story2_trial_8.wav,2,2,1,aske_story2_trial_8.wav,marianne_story4_trial_20.wav,192,1,1188249,1227409,1.274740
20,2397.283203,2494.246094,DTU,left,marianne_story4_trial_21.wav,aske_story2_trial_9.wav,2,2,1,aske_story2_trial_9.wav,marianne_story4_trial_21.wav,133,2,1227409,1277054,1.616048
21,2645.845703,2724.332031,DTU,left,marianne_story4_trial_22.wav,aske_story2_trial_10.wav,2,2,1,aske_story2_trial_10.wav,marianne_story4_trial_22.wav,224,3,1354673,1394858,1.308105
22,2724.332031,2803.433594,DTU,left,marianne_story4_trial_23.wav,aske_story2_trial_11.wav,2,2,1,aske_story2_trial_11.wav,marianne_story4_trial_23.wav,224,3,1394858,1435358,1.318359
23,2877.552734,2960.062500,DTU,right,marianne_story3_trial_1.wav,aske_story4_trial_1.wav,2,1,2,aske_story4_trial_1.wav,marianne_story3_trial_1.wav,132,2,1473307,1515552,1.375163
24,2960.062500,3053.441406,DTU,left,aske_story4_trial_2.wav,marianne_story3_trial_2.wav,2,1,1,aske_story4_trial_2.wav,marianne_story3_trial_2.wav,141,1,1515552,1563362,1.556315
25,3053.441406,3134.685547,DTU,right,marianne_story3_trial_3.wav,aske_story4_trial_3.wav,2,1,2,aske_story4_trial_3.wav,marianne_story3_trial_3.wav,132,2,1563362,1604959,1.354069
26,3134.685547,3230.324219,DTU,right,marianne_story3_trial_4.wav,aske_story4_trial_4.wav,2,1,2,aske_story4_trial_4.wav,marianne_story3_trial_4.wav,248,3,1604959,1653926,1.593978
27,3230.324219,3308.248047,DTU,left,aske_story4_trial_5.wav,marianne_story3_trial_5.wav,2,1,1,aske_story4_trial_5.wav,marianne_story3_trial_5.wav,240,3,1653926,1693823,1.298730
28,3308.248047,3684.783203,DTU,right,marianne_story3_trial_6.wav,aske_story4_trial_6.wav,2,1,2,aske_story4_trial_6.wav,marianne_story3_trial_6.wav,248,3,1693823,1886609,6.275586
29,3684.783203,3760.251953,DTU,left,aske_story4_trial_7.wav,marianne_story3_trial_7.wav,2,1,1,aske_story4_trial_7.wav,marianne_story3_trial_7.wav,141,1,1886609,1925249,1.257812
30,3760.251953,3835.798828,DTU,left,aske_story4_trial_8.wav,marianne_story3_trial_8.wav,2,1,1,aske_story4_trial_8.wav,marianne_story3_trial_8.wav,137,2,1925249,1963929,1.259115
31,3835.798828,3914.769531,DTU,right,marianne_story3_trial_9.wav,aske_story4_trial_9.wav,2,1,2,aske_story4_trial_9.wav,marianne_story3_trial_9.wav,160,1,1963929,2004362,1.316178
32,3981.472656,4054.638672,DTU,right,marianne_story3_trial_10.wav,aske_story4_trial_10.wav,2,1,2,aske_story4_trial_10.wav,marianne_story3_trial_10.wav,248,3,2038514,2075975,1.219434
33,4120.060547,4197.933594,DTU,left,aske_story6_trial_1.wav,marianne_story3_trial_11.wav,2,1,1,aske_story6_trial_1.wav,marianne_story3_trial_11.wav,137,2,2109471,2149342,1.297884
34,4197.933594,4277.201172,DTU,right,marianne_story3_trial_12.wav,aske_story6_trial_2.wav,2,1,2,aske_story6_trial_2.wav,marianne_story3_trial_12.wav,248,3,2149342,2189927,1.321126
35,4277.201172,4360.449219,DTU,left,aske_story6_trial_3.wav,marianne_story3_trial_13.wav,2,1,1,aske_story6_trial_3.wav,marianne_story3_trial_13.wav,240,3,2189927,2232550,1.387467
36,4435.212891,4509.964844,DTU,right,marianne_story3_trial_14.wav,aske_story6_trial_4.wav,2,1,2,aske_story6_trial_4.wav,marianne_story3_trial_14.wav,132,2,2270829,2309102,1.245866
37,4509.964844,4582.349609,DTU,left,aske_story6_trial_5.wav,marianne_story3_trial_15.wav,2,1,1,aske_story6_trial_5.wav,marianne_story3_trial_15.wav,137,2,2309102,2346163,1.206413
38,4582.349609,4665.068359,DTU,right,marianne_story3_trial_16.wav,aske_story6_trial_6.wav,2,1,2,aske_story6_trial_6.wav,marianne_story3_trial_16.wav,132,2,2346163,2388515,1.378646
39,4665.068359,4737.855469,DTU,left,aske_story6_trial_7.wav,marianne_story3_trial_17.wav,2,1,1,aske_story6_trial_7.wav,marianne_story3_trial_17.wav,137,2,2388515,2425782,1.213118
40,4737.855469,4825.279297,DTU,left,marianne_story1_trial_1.wav,aske_story5_trial_1.wav,2,2,1,aske_story5_trial_1.wav,marianne_story1_trial_1.wav,192,1,2425782,2470543,1.457064
41,4825.279297,4902.683594,DTU,left,marianne_story1_trial_2.wav,aske_story5_trial_2.wav,2,2,1,aske_story5_trial_2.wav,marianne_story1_trial_2.wav,192,1,2470543,2510174,1.290072
42,4902.683594,4974.708984,DTU,left,marianne_story1_trial_3.wav,aske_story5_trial_3.wav,2,2,1,aske_story5_trial_3.wav,marianne_story1_trial_3.wav,224,3,2510174,2547051,1.200423
43,4974.708984,5048.275391,DTU,right,aske_story5_trial_4.wav,marianne_story2_trial_1.wav,2,2,2,aske_story5_trial_4.wav,marianne_story2_trial_1.wav,131,3,2547051,2584717,1.226107
44,5048.275391,5125.861328,DTU,left,marianne_story2_trial_2.wav,aske_story5_trial_5.wav,2,2,1,aske_story5_trial_5.wav,marianne_story2_trial_2.wav,224,3,2584717,2624441,1.293099
45,5125.861328,5215.802734,DTU,right,aske_story5_trial_6.wav,marianne_story2_trial_3.wav,2,2,2,aske_story5_trial_6.wav,marianne_story2_trial_3.wav,135,1,2624441,2670491,1.499023
46,5215.802734,5287.876953,DTU,right,aske_story5_trial_7.wav,marianne_story2_trial_4.wav,2,2,2,aske_story5_trial_7.wav,marianne_story2_trial_4.wav,135,1,2670491,2707393,1.201237
47,5287.876953,5368.785156,DTU,right,aske_story5_trial_8.wav,marianne_story2_trial_5.wav,2,2,2,aske_story5_trial_8.wav,marianne_story2_trial_5.wav,150,2,2707393,2748818,1.348470
48,5368.785156,5461.425781,DTU,right,aske_story5_trial_9.wav,marianne_story2_trial_6.wav,2,2,2,aske_story5_trial_9.wav,marianne_story2_trial_6.wav,135,1,2748818,2796250,1.544010
49,5461.425781,5530.214844,DTU,left,aske_story3_trial_1.wav,marianne_story5_trial_1.wav,2,1,1,aske_story3_trial_1.wav,marianne_story5_trial_1.wav,141,1,2796250,2831470,1.146484
50,5530.214844,5606.304688,DTU,right,marianne_story5_trial_2.wav,aske_story3_trial_2.wav,2,1,2,aske_story3_trial_2.wav,marianne_story5_trial_2.wav,160,1,2831470,2870428,1.268164
51,5606.304688,5687.125000,DTU,right,marianne_story5_trial_3.wav,aske_story3_trial_3.wav,2,1,2,aske_story3_trial_3.wav,marianne_story5_trial_3.wav,248,3,2870428,2911808,1.347005
52,5687.125000,5761.304688,DTU,left,aske_story3_trial_4.wav,marianne_story5_trial_4.wav,2,1,1,aske_story3_trial_4.wav,marianne_story5_trial_4.wav,137,2,2911808,2949788,1.236328
53,5761.304688,5835.382812,DTU,right,marianne_story5_trial_5.wav,aske_story3_trial_5.wav,2,1,2,aske_story3_trial_5.wav,marianne_story5_trial_5.wav,160,1,2949788,2987716,1.234635
54,5835.382812,5908.919922,DTU,left,aske_story3_trial_6.wav,marianne_story5_trial_6.wav,2,1,1,aske_story3_trial_6.wav,marianne_story5_trial_6.wav,240,3,2987716,3025367,1.225618
55,5908.919922,5981.490234,DTU,left,aske_story3_trial_7.wav,marianne_story5_trial_7.wav,2,1,1,aske_story3_trial_7.wav,marianne_story5_trial_7.wav,141,1,3025367,3062523,1.209505
56,5981.490234,6066.707031,DTU,right,marianne_story5_trial_8.wav,aske_story3_trial_8.wav,2,1,2,aske_story3_trial_8.wav,marianne_story5_trial_8.wav,160,1,3062523,3106154,1.420280
57,6066.707031,6151.800781,DTU,right,marianne_story5_trial_9.wav,aske_story3_trial_9.wav,2,1,2,aske_story3_trial_9.wav,marianne_story5_trial_9.wav,248,3,3106154,3149722,1.418229
58,6151.800781,6236.289062,DTU,right,marianne_story5_trial_10.wav,aske_story3_trial_10.wav,2,1,2,aske_story3_trial_10.wav,marianne_story5_trial_10.wav,132,2,3149722,3192980,1.408138
59,6236.289062,6326.000000,DTU,right,marianne_story5_trial_11.wav,aske_story3_trial_11.wav,2,1,2,aske_story3_trial_11.wav,marianne_story5_trial_11.wav,160,1,3192980,3238912,1.495182

In [2]:
#raw eeg
print("-------------Raw EEG of 1 trial-----------")

raw = nwb.acquisition["trial_10_EEG_raw"]
print(raw)
print("shape:", raw.data.shape)
print("fs:", raw.rate)

-------------Raw EEG of 1 trial-----------
trial_10_EEG_raw pynwb.base.TimeSeries at 0x140616112606080
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (37663, 73), type "<f8">
  description: Raw EEG signal
  offset: 0.0
  rate: 512.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: microvolts

shape: (37663, 73)
fs: 512.0

In [3]:
#preprocessed EEG
print("---------------EEGPP-------------")
eeg_proc = nwb.processing["eeg_preprocessed"]
pp = eeg_proc.data_interfaces["trial_10_EEG_preprocessed"]
print(pp)
print("shape:", pp.data.shape)
print("fs:", pp.rate)

---------------EEGPP-------------
trial_10_EEG_preprocessed pynwb.ecephys.ElectricalSeries at 0x140616112612272
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (2354, 73), type "<f8">
  description: Preprocessed EEG
  electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
  offset: 0.0
  rate: 32.0
  resolution: -1.0
  starting_time: 0.0
  starting_time_unit: seconds
  unit: volts

shape: (2354, 73)
fs: 32.0

In [4]:
#electrode metadata
elec_df = nwb.electrodes.to_dataframe()
elec_df

,location,group,label,group_name,x,y,z,imp
id,,,,,,,,
0,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch1,EEG_group,NaN,NaN,NaN,NaN
1,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch2,EEG_group,NaN,NaN,NaN,NaN
2,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch3,EEG_group,NaN,NaN,NaN,NaN
3,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch4,EEG_group,NaN,NaN,NaN,NaN
4,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch5,EEG_group,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
68,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch69,EEG_group,NaN,NaN,NaN,NaN
69,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch70,EEG_group,NaN,NaN,NaN,NaN
70,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch71,EEG_group,NaN,NaN,NaN,NaN
71,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch72,EEG_group,NaN,NaN,NaN,NaN
72,scalp,EEG_group pynwb.ecephys.ElectrodeGroup at 0x14...,ch73,EEG_group,NaN,NaN,NaN,NaN

In [5]:
import re

eeg_proc = nwb.processing["eeg_preprocessed"]

def tid_from_key(k):
    m = re.match(r"trial_(\d+)_EEG_preprocessed$", k)
    return int(m.group(1)) if m else None

keys = sorted(eeg_proc.data_interfaces.keys(), key=lambda k: tid_from_key(k) or 10**9)

for k in keys:
    ts = eeg_proc.data_interfaces[k]
    tid = tid_from_key(k)
    dur = ts.data.shape[0] / ts.rate
    print(tid, k, ts.data.shape, dur)

1 trial_1_EEG_preprocessed (2671, 73) 83.46875
2 trial_2_EEG_preprocessed (2647, 73) 82.71875
3 trial_3_EEG_preprocessed (2520, 73) 78.75
4 trial_4_EEG_preprocessed (5080, 73) 158.75
6 trial_6_EEG_preprocessed (2565, 73) 80.15625
7 trial_7_EEG_preprocessed (2967, 73) 92.71875
9 trial_9_EEG_preprocessed (2590, 73) 80.9375
10 trial_10_EEG_preprocessed (2354, 73) 73.5625
13 trial_13_EEG_preprocessed (3332, 73) 104.125
14 trial_14_EEG_preprocessed (5048, 73) 157.75
15 trial_15_EEG_preprocessed (2901, 73) 90.65625
16 trial_16_EEG_preprocessed (2537, 73) 79.28125
17 trial_17_EEG_preprocessed (2580, 73) 80.625
18 trial_18_EEG_preprocessed (2911, 73) 90.96875
19 trial_19_EEG_preprocessed (2721, 73) 85.03125
20 trial_20_EEG_preprocessed (3169, 73) 99.03125
21 trial_21_EEG_preprocessed (2663, 73) 83.21875
22 trial_22_EEG_preprocessed (8875, 73) 277.34375
23 trial_23_EEG_preprocessed (2391, 73) 74.71875
24 trial_24_EEG_preprocessed (2448, 73) 76.5
25 trial_25_EEG_preprocessed (3103, 73) 96.96875
28 trial_28_EEG_preprocessed (2512, 73) 78.5
29 trial_29_EEG_preprocessed (2532, 73) 79.125
31 trial_31_EEG_preprocessed (2641, 73) 82.53125
32 trial_32_EEG_preprocessed (2989, 73) 93.40625
33 trial_33_EEG_preprocessed (2600, 73) 81.25
34 trial_34_EEG_preprocessed (3061, 73) 95.65625
35 trial_35_EEG_preprocessed (2494, 73) 77.9375
36 trial_36_EEG_preprocessed (12050, 73) 376.5625
37 trial_37_EEG_preprocessed (2415, 73) 75.46875
38 trial_38_EEG_preprocessed (2418, 73) 75.5625
39 trial_39_EEG_preprocessed (2528, 73) 79.0
41 trial_41_EEG_preprocessed (2342, 73) 73.1875
43 trial_43_EEG_preprocessed (2492, 73) 77.875
44 trial_44_EEG_preprocessed (2537, 73) 79.28125
45 trial_45_EEG_preprocessed (2664, 73) 83.25
47 trial_47_EEG_preprocessed (2393, 73) 74.78125
48 trial_48_EEG_preprocessed (2317, 73) 72.40625
49 trial_49_EEG_preprocessed (2647, 73) 82.71875
50 trial_50_EEG_preprocessed (2330, 73) 72.8125
51 trial_51_EEG_preprocessed (2798, 73) 87.4375
52 trial_52_EEG_preprocessed (2477, 73) 77.40625
53 trial_53_EEG_preprocessed (2305, 73) 72.03125
54 trial_54_EEG_preprocessed (2355, 73) 73.59375
55 trial_55_EEG_preprocessed (2483, 73) 77.59375
56 trial_56_EEG_preprocessed (2879, 73) 89.96875
57 trial_57_EEG_preprocessed (2307, 73) 72.09375
58 trial_58_EEG_preprocessed (2590, 73) 80.9375
59 trial_59_EEG_preprocessed (2965, 73) 92.65625
60 trial_60_EEG_preprocessed (2202, 73) 68.8125
61 trial_61_EEG_preprocessed (2435, 73) 76.09375
62 trial_62_EEG_preprocessed (2587, 73) 80.84375
63 trial_63_EEG_preprocessed (2374, 73) 74.1875
64 trial_64_EEG_preprocessed (2371, 73) 74.09375
65 trial_65_EEG_preprocessed (2354, 73) 73.5625
66 trial_66_EEG_preprocessed (2323, 73) 72.59375
67 trial_67_EEG_preprocessed (2727, 73) 85.21875
68 trial_68_EEG_preprocessed (2723, 73) 85.09375
69 trial_69_EEG_preprocessed (2704, 73) 84.5
70 trial_70_EEG_preprocessed (2871, 73) 89.71875